"""make published_at nullable or default

Revision ID: 216555583b2b
Revises: 9c14edbd7a80
Create Date: 2026-05-23 15:23:28.507099

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '216555583b2b'
down_revision: str | Sequence[str] | None = '9c14edbd7a80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
